import type { OfficeObject } from "@/types/office";

export const officeObjects: OfficeObject[] = [
  {
    id: "projects",
    kind: "laptop",
    label: "Laptop",
    title: "Proyectos",
    body: "Casos seleccionados de UX/UI, diseño web y producto digital. Aquí viven los proyectos donde transformo ideas complejas en experiencias claras.",
    modelPath: "/models/laptop.glb",
    position: [-1.45, 0.42, 0.05],
    rotation: [0, 0.2, 0],
    scale: 1,
    focusPosition: [-1.15, 1.2, 2.5],
  },
  {
    id: "about",
    kind: "coffee",
    label: "Café",
    title: "Sobre mí",
    body: "Soy Catherine, diseñadora UX/UI y diseñadora digital. Me gusta unir diseño, tecnología e IA para crear experiencias útiles, humanas y visualmente cuidadas.",
    modelPath: "/models/coffee.glb",
    position: [0.3, 0.54, 0.2],
    scale: 1,
    focusPosition: [0.25, 1.25, 2.35],
  },
  {
    id: "beyond",
    kind: "aurora",
    label: "Aurora",
    title: "Más allá del diseño",
    body: "También soy café, cerro, running, gatos y pequeñas obsesiones creativas. Aurora suele acompañar mis procesos.",
    modelPath: "/models/aurora.glb",
    position: [1.7, 0.35, -0.05],
    rotation: [0, -0.65, 0],
    scale: 1,
    focusPosition: [1.35, 1.15, 2.45],
  },
  {
    id: "visual",
    kind: "camera",
    label: "Cámara",
    title: "Diseño visual",
    body: "Branding, logos, redes sociales, piezas gráficas e invitaciones digitales. Diseño visual con intención, no solo decoración.",
    modelPath: "/models/camera.glb",
    position: [-2.05, 0.48, -0.95],
    rotation: [0, 0.45, 0],
    scale: 1,
    focusPosition: [-1.75, 1.2, 2.15],
  },
  {
    id: "timeline",
    kind: "window",
    label: "Ventana",
    title: "Timeline",
    body: "De Venezuela a Chile, del diseño gráfico al producto digital, y de la curiosidad por la tecnología a integrar IA y frontend en mi trabajo.",
    modelPath: "/models/window.glb",
    position: [0.95, 1.75, -1.85],
    scale: 1,
    focusPosition: [0.75, 2.1, 1.8],
  },
  {
    id: "process",
    kind: "notebook",
    label: "Libreta",
    title: "Proceso",
    body: "Entender, ordenar, diseñar, validar y mejorar. Me gusta convertir el caos inicial en una experiencia clara.",
    modelPath: "/models/notebook.glb",
    position: [1.05, 0.44, 0.72],
    rotation: [0, -0.3, 0],
    scale: 1,
    focusPosition: [0.95, 1.2, 2.3],
  },
];
