import type { OfficeObject } from "@/types/office";

export const officeObjects: OfficeObject[] = [
  {
    id: "projects",
    kind: "laptop",
    label: "Laptop",
    title: "Proyectos",
    body: "Casos seleccionados de UX/UI, diseño web y producto digital. Aquí viven los proyectos donde transformo ideas complejas en experiencias claras.",
    modelPath: "/models/macbook/model.obj",
    futureAction: "Hook preparado: Entrar a la PC / DigitalWorld.",
    position: [-0.55, 0.62, -0.22],
    rotation: [0, 0.08, 0],
    scale: 1.15,
    focusPosition: [-0.55, 1.35, 2.25],
  },
  {
    id: "about",
    kind: "coffee",
    label: "Café",
    title: "Sobre mí",
    body: "Soy Catherine, diseñadora UX/UI y diseñadora digital. Me gusta unir diseño, tecnología e IA para crear experiencias útiles, humanas y visualmente cuidadas.",
    modelPath: "/models/coffee.glb",
    position: [0.36, 0.72, 0.18],
    scale: 0.92,
    focusPosition: [0.35, 1.24, 2.2],
  },
  {
    id: "beyond",
    kind: "aurora",
    label: "Aurora",
    title: "Más allá del diseño",
    body: "También soy café, cerro, running, gatos y pequeñas obsesiones creativas. Aurora suele acompañar mis procesos.",
    modelPath: "/models/aurora.glb",
    position: [2.16, 1.22, -1.82],
    rotation: [0, -0.9, 0],
    scale: 0.48,
    focusPosition: [1.95, 1.65, 1.35],
  },
  {
    id: "visual",
    kind: "camera",
    label: "Cámara",
    title: "Diseño visual",
    body: "Branding, logos, redes sociales, piezas gráficas e invitaciones digitales. Diseño visual con intención, no solo decoración.",
    modelPath: "/models/camera.glb",
    position: [-2.1, 1.7, -2.28],
    rotation: [0, 0, 0],
    scale: 0.32,
    focusPosition: [-2.08, 1.82, 1.2],
  },
  {
    id: "timeline",
    kind: "window",
    label: "Ventana",
    title: "Timeline",
    body: "De Venezuela a Chile, del diseño gráfico al producto digital, y de la curiosidad por la tecnología a integrar IA y frontend en mi trabajo.",
    modelPath: "/models/window.glb",
    position: [1.15, 1.58, -2.38],
    scale: 0.92,
    focusPosition: [0.95, 1.95, 1.85],
  },
  {
    id: "process",
    kind: "notebook",
    label: "Libreta",
    title: "Proceso",
    body: "Entender, ordenar, diseñar, validar y mejorar. Me gusta convertir el caos inicial en una experiencia clara.",
    modelPath: "/models/notebook.glb",
    position: [1.05, 0.7, 0.36],
    rotation: [0, -0.58, 0],
    scale: 0.92,
    focusPosition: [0.95, 1.18, 2.08],
  },
];
